services:
  payload:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm@10.23.0 --force && pnpm -v && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  seed:
    image: node:22-alpine
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm@10.23.0 --force && pnpm install && pnpm run seed:focus-areas"
    depends_on:
      - postgres
    env_file:
      - .env
    profiles:
      - seed
      
  postgres:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: oddtopsy_reports
      POSTGRES_USER: oddtopsy
      POSTGRES_PASSWORD: 0ddTopsy
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules: